### ISSUE TITLE
inject without head tag

### ISSUE THREAD

**Issue by aigan** [dpikt/modulepreload#1]
I was so close to upload my own version of modulepreload injection library, and saw this.
It seem to work. Except for files where I excluded the head tag. 
Could you fall back to put them at the end of file, or after the DOCTYPE?

**Comment by dpikt** [comment]
Hi @aigan, glad to hear it’s working for you! I didn’t consider the case of documents with no head tag. I’ll add a fallback to put the preloads at the top of the file in that case.

**Comment by dpikt** [comment]
@aigan pushed an update in 1.1.0.
